# Generated by Django 4.2.27 on 2026-09-18 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_useremploymenthistory_soc_detailed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='tool_tip_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='faq',
            name='permission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.permissiontype'),
        ),
        migrations.AddField(
            model_name='faq',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.project'),
        ),
    ]
