# Generated by Django 4.2.27 on 2026-10-08 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_rename_tool_tip_name_faq_title_faq_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='permission_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='core.permissiontype'),
        ),
    ]
