# Generated by Django 4.2.27 on 2026-10-08 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_faq_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='author',
            field=models.ForeignKey(blank=True, help_text='user who created entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='review_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='user who approved the entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
